"""manifest.json and NOTICE.txt for a world folder (world/FORMAT.md section 4).

The manifest lists every file with its byte size and sha256, the coordinate
frame, the height levels, where the data came from and under what licence,
and the robots.txt decisions the data was fetched under. NOTICE.txt carries
the credits and the CC BY 4.0 attribution in plain ASCII text.
"""

import gzip
import hashlib
import json
import os
import re
import subprocess
import zlib
from pathlib import Path

from . import __version__, codec
from .sources import CC_BY_4_URL, CREDIT_SSR, DATASETS

FORMAT_NAME = "commons-world"
FORMAT_VERSION = 1
MANIFEST_NAME = "manifest.json"
NOTICE_NAME = "NOTICE.txt"

_ASCII_FOLD = {
    "\u00a9": "(c)", "\u00e5": "aa", "\u00c5": "Aa", "\u00f8": "o", "\u00d8": "O",
    "\u00e6": "ae", "\u00c6": "Ae", "\u00ab": '"', "\u00bb": '"', "\u2013": "-",
    "\u2014": "-", "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
}
_CHUNK_KEY = re.compile(r"^-?\d+_-?\d+$")


def dumps_json(obj, indent=1):
    """JSON bytes as FORMAT.md wants them: ASCII only, keys sorted, one trailing newline."""
    text = json.dumps(obj, ensure_ascii=True, sort_keys=True, indent=indent,
                      separators=(",", ": ") if indent is not None else (",", ":"),
                      allow_nan=False)
    return (text + "\n").encode("ascii")


def sha256_hex(data):
    return hashlib.sha256(data).hexdigest()


def file_entry(folder, relpath):
    """{"file", "bytes", "sha256"} for a file already written in the world folder."""
    data = (Path(folder) / relpath).read_bytes()
    return {"file": relpath, "bytes": len(data), "sha256": sha256_hex(data)}


def ascii_fold(text):
    """Plain-ASCII rendering of a credit, for NOTICE.txt."""
    out = "".join(_ASCII_FOLD.get(ch, ch) for ch in text)
    return out.encode("ascii", errors="replace").decode("ascii")


def pipeline_commit(repo_dir=None):
    """Short commit of the pipeline's checkout, with "-dirty" if world/pipeline has changes.

    Uses read-only git commands only, with GIT_OPTIONAL_LOCKS=0 so that `git
    status` does not refresh the index either. None if git is not available.
    """
    repo_dir = Path(repo_dir or Path(__file__).resolve().parents[1])
    run = dict(cwd=repo_dir, capture_output=True, text=True, timeout=10, check=True,
               env=dict(os.environ, GIT_OPTIONAL_LOCKS="0"))
    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], **run).stdout.strip()
        status = subprocess.run(["git", "status", "--porcelain", "--", "."], **run
                                ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    return commit + ("-dirty" if status else "") if commit else None


def build_manifest(*, world_id, generated_at, crs, levels, files, sources, credits, robots,
                   stats=None, commit=None):
    """The manifest object. `levels` entries are FORMAT.md's level records."""
    return {
        "format": FORMAT_NAME,
        "version": FORMAT_VERSION,
        "id": world_id,
        "generated_at": generated_at,
        "pipeline": {"version": __version__, "commit": commit},
        "crs": crs,
        "levels": levels,
        "files": files,
        "sources": sources,
        "credits": credits,
        "robots": robots,
        "stats": stats or {},
    }


def notice_text(*, world_id, generated_at, credits, sources, commit=None, synthetic=False):
    """NOTICE.txt: credits, sources and the licence, in plain ASCII."""
    lines = ["Commons World data folder: {}".format(world_id), "",
             "Generated by the Commons World pipeline {} (commit {}) at {}.".format(
                 __version__, commit or "unknown", generated_at), ""]
    if synthetic:
        lines += ["This is a synthetic world. Every height, parcel and listing value in it",
                  "was generated by commons_world/synthetic.py. It contains no real data",
                  "and describes no real place.", ""]
    if credits:
        lines.append("Credits")
        lines += ["- " + ascii_fold(c) for c in credits]
        lines.append("")
    if sources:
        lines.append("Sources")
        for s in sources:
            parts = ["- {}: {}".format(ascii_fold(s.get("name", "")), ascii_fold(s.get("publisher", "")))]
            if s.get("licence"):
                parts.append("  Licence: {}{}".format(
                    s["licence"], " ({})".format(s["licence_url"]) if s.get("licence_url") else ""))
            if s.get("endpoint"):
                parts.append("  Endpoint: {}".format(s["endpoint"]))
            if s.get("retrieved"):
                parts.append("  Retrieved: {}".format(s["retrieved"]))
            if s.get("modified"):
                parts.append("  Changes: {}".format(ascii_fold(s["modified"])))
            if s.get("note"):
                parts.append("  Note: {}".format(ascii_fold(s["note"])))
            lines += parts
        lines.append("")
    if any(s.get("licence") == "CC BY 4.0" for s in sources or []):
        lines += [
            "Licence",
            "Data from Kartverket in this folder is used under the Creative Commons",
            "Attribution 4.0 International licence (CC BY 4.0), " + CC_BY_4_URL + ".",
            "It has been modified as described above. Kartverket does not endorse this",
            "world or its use of the data.",
            "",
        ]
    lines += [
        "No OpenStreetMap data is used in this folder.",
        "",
        "The credits above are written in ASCII. The exact credit strings, with their",
        "original characters, are listed under \"credits\" in manifest.json.",
    ]
    return ("\n".join(lines) + "\n").encode("ascii")


def write_manifest(folder, manifest):
    """Write manifest.json into the world folder and return its path."""
    path = Path(folder) / MANIFEST_NAME
    path.write_bytes(dumps_json(manifest))
    return path


def _check_chunk(where, level, key, entry, data, epsg, problems):
    """Read one height chunk and check it against its key, its level and its manifest entry."""
    try:
        payload = gzip.decompress(data)
        chunk = codec.decode(payload)
    except (OSError, EOFError, ValueError, zlib.error) as exc:
        problems.append("{}: not a readable CWH1 chunk ({})".format(where, exc))
        return
    name = str(entry.get("file", ""))
    if not name.endswith(".{}.cwh.gz".format(codec.hash8(payload))):
        problems.append("{}: file name hash does not match its contents".format(where))
    try:
        i, j = (int(v) for v in key.split("_"))
        cell = float(level["cell"])
        samples = int(level["chunk_samples"])
        apron = int(level["apron"])
    except (KeyError, TypeError, ValueError):
        return  # reported by the shape checks
    side, pad, stored = samples * cell, apron * cell, samples + 2 * apron
    expected = {
        "width": stored, "height": stored, "cell_cm": int(round(cell * 100)),
        "corner_e_dm": int(round((i * side - pad) * 10)),
        "corner_n_dm": int(round(((j + 1) * side + pad) * 10)),
        "epsg": epsg, "reserved": 0, "apron": apron == 1,
    }
    for field, want in expected.items():
        if chunk[field] != want:
            problems.append("{}: header {} is {}, expected {}".format(where, field, chunk[field],
                                                                      want))
    if level.get("class_band") and chunk["classes"] is None:
        problems.append("{}: the level has a class band but this chunk has none".format(where))
    dm = chunk["heights_dm"]
    if int(dm.min()) != chunk["base_dm"]:
        problems.append("{}: base {} dm is not the chunk minimum {} dm".format(
            where, chunk["base_dm"], int(dm.min())))
    if int(dm.max()) <= 0:
        problems.append("{}: every sample is at or below 0 m, so it should be listed as sea"
                        .format(where))
    for field, value in (("min", int(dm.min())), ("max", int(dm.max()))):
        if entry.get(field) != round(value / 10.0, 1):
            problems.append("{}: manifest {} {} does not match the chunk's {}".format(
                where, field, entry.get(field), round(value / 10.0, 1)))


def _check_credits(folder, manifest, problems):
    """NOTICE.txt must be there, and the credits the sources need must be given."""
    entry = manifest["files"].get("notice")
    if not isinstance(entry, dict) or entry.get("file") != NOTICE_NAME:
        problems.append("files.notice: {} must be listed".format(NOTICE_NAME))
        return
    try:
        notice = (folder / NOTICE_NAME).read_bytes().decode("ascii")
    except (OSError, UnicodeDecodeError) as exc:
        problems.append("{} unreadable or not ASCII: {}".format(NOTICE_NAME, exc))
        return
    credits = [str(c) for c in manifest["credits"]]
    sources = [s for s in manifest["sources"] if isinstance(s, dict)]
    for credit in credits:
        if ascii_fold(credit) not in notice:
            problems.append("{} does not carry the credit {!r}".format(NOTICE_NAME, credit))
    if "No OpenStreetMap data" not in notice:
        problems.append("{} does not say that no OpenStreetMap data is used".format(NOTICE_NAME))
    kartverket = (any("CC BY" in str(s.get("licence", "")) for s in sources)
                  or any(level.get("source") for level in manifest["levels"]))
    if kartverket:
        if not any("Kartverket" in c and "CC BY 4.0" in c for c in credits):
            problems.append("credits: Kartverket data needs the Kartverket CC BY 4.0 credit")
        if CC_BY_4_URL not in notice:
            problems.append("{} does not link the CC BY 4.0 licence".format(NOTICE_NAME))
    if any(s.get("dataset_uuid") == DATASETS["ssr"]["uuid"] for s in sources) \
            and CREDIT_SSR not in credits:
        problems.append("credits: place names need the SSR credit")


def _check_site(manifest, problems):
    """crs.lat_deg, crs.lon_deg and crs.time_zone, each checked only when present.

    The latitude and longitude, if either is there, must both be, and must be the origin's
    own (geo.to_latlon) within 1e-4 deg; the zone must be one the build can write.
    """
    import math

    from . import geo
    from .build import ALLOWED_TIME_ZONES

    crs = manifest["crs"]
    if "lat_deg" in crs or "lon_deg" in crs:
        lat, lon = crs.get("lat_deg"), crs.get("lon_deg")
        if not all(isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)
                   for v in (lat, lon)):
            problems.append("crs.lat_deg and crs.lon_deg must both be present and finite")
        else:
            try:
                want = geo.to_latlon(float(crs["origin_e"]), float(crs["origin_n"]),
                                     int(crs["epsg"]))
            except (KeyError, TypeError, ValueError) as exc:
                problems.append("crs: cannot check lat_deg and lon_deg: {}".format(exc))
            else:
                if abs(lat - want[0]) > 1e-4 or abs(lon - want[1]) > 1e-4:
                    problems.append("crs.lat_deg, crs.lon_deg ({}, {}) are not the origin's "
                                    "({:.6f}, {:.6f})".format(lat, lon, want[0], want[1]))
    if "time_zone" in crs and crs["time_zone"] not in ALLOWED_TIME_ZONES:
        problems.append("crs.time_zone {!r} is not one of {}".format(
            crs["time_zone"], ", ".join(ALLOWED_TIME_ZONES)))


FACTS_BLOCKS = ("plot", "sun", "access")


def _check_facts(folder, manifest, problems):
    """facts.json, when listed: ASCII JSON of version 1 whose blocks carry a method and caveats."""
    entry = manifest["files"].get("facts")
    if not isinstance(entry, dict):
        return
    try:
        facts = json.loads((folder / str(entry.get("file", ""))).read_bytes().decode("ascii"))
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        problems.append("files.facts: unreadable or not ASCII JSON: {}".format(exc))
        return
    if not isinstance(facts, dict) or facts.get("version") != 1:
        problems.append("files.facts: version must be 1")
        return
    if not isinstance(facts.get("generated_at"), str):
        problems.append("files.facts: generated_at missing")
    for name in FACTS_BLOCKS:
        block = facts.get(name)
        if block is None:
            continue               # the viewer says "not computed"
        if not isinstance(block, dict) or not isinstance(block.get("method"), str) \
                or not isinstance(block.get("caveats"), list):
            problems.append("files.facts: block {!r} needs a method string and a caveats "
                            "list".format(name))
    sun = facts.get("sun")
    horizon = sun.get("horizon") if isinstance(sun, dict) else None
    beyond = horizon.get("beyond_world") if isinstance(horizon, dict) else None
    if beyond is not None:
        for key in ("from_m", "profile_deg", "distance_m"):
            value = beyond.get(key) if isinstance(beyond, dict) else None
            if not isinstance(value, list) or len(value) != 720:
                problems.append("files.facts: sun.horizon.beyond_world.{} must hold 720 "
                                "values".format(key))


def _check_listing(folder, manifest, problems):
    """listing.json, if listed, passes the build's own leak check and schema again.

    The build refuses a listing that carries private group data; `check` is the natural
    gate before anything is published, so it re-reads the file rather than trusting it.
    """
    from . import listing as listinglib

    entry = manifest["files"].get("listing")
    if not entry or not (folder / str(entry.get("file", ""))).is_file():
        return
    try:
        record = json.loads((folder / entry["file"]).read_bytes().decode("ascii"))
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        problems.append("files.listing: unreadable or not ASCII JSON: {}".format(exc))
        return
    if not isinstance(record, dict):
        problems.append("files.listing: not a JSON object")
        return
    try:
        listinglib.check_listing(record)
    except (listinglib.LeakError, listinglib.ListingInvalid) as exc:
        problems.append("files.listing: {}".format(exc))


def check_world(folder):
    """Problems with a built world folder, as strings (empty when sound).

    Checks the manifest's shape; that every file it lists exists with the
    stated size and sha256, and that every file in the folder is listed; that
    every height chunk's header agrees with its key, its level, its file name
    and its manifest entry; and that NOTICE.txt and the credits the sources
    need are there; that facts.json, if listed, is version 1 with a
    method and caveats on each block; and that listing.json, if listed,
    still passes the listing leak check and schema.
    """
    folder = Path(folder)
    problems = []
    path = folder / MANIFEST_NAME
    try:
        raw = path.read_bytes()
        raw.decode("ascii")
        manifest = json.loads(raw)
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        return ["manifest.json unreadable or not ASCII JSON: {}".format(exc)]
    required = {"format": str, "version": int, "id": str, "generated_at": str,
                "pipeline": dict, "crs": dict, "levels": list, "files": dict,
                "sources": list, "credits": list, "robots": list, "stats": dict}
    for key, kind in required.items():
        if not isinstance(manifest.get(key), kind):
            problems.append("manifest.{} missing or not a {}".format(key, kind.__name__))
    if problems:
        return problems
    if manifest["format"] != FORMAT_NAME or manifest["version"] != FORMAT_VERSION:
        problems.append("unknown format/version {} {}".format(manifest["format"], manifest["version"]))
    for key in ("epsg", "origin_e", "origin_n", "grid_north_offset_deg", "scale_factor", "vertical"):
        if key not in manifest["crs"]:
            problems.append("crs.{} missing".format(key))
    _check_site(manifest, problems)
    listed = set()

    def check_entry(where, entry):
        """The file's bytes if it exists as listed, else None (problems recorded)."""
        for key in ("file", "bytes", "sha256"):
            if key not in entry:
                problems.append("{}: {} missing".format(where, key))
                return None
        target = folder / entry["file"]
        listed.add(entry["file"])
        if not target.is_file():
            problems.append("{}: {} does not exist".format(where, entry["file"]))
            return None
        data = target.read_bytes()
        if len(data) != entry["bytes"]:
            problems.append("{}: {} is {} bytes, manifest says {}".format(
                where, entry["file"], len(data), entry["bytes"]))
        if sha256_hex(data) != entry["sha256"]:
            problems.append("{}: {} sha256 does not match".format(where, entry["file"]))
        return data

    for level in manifest["levels"]:
        name = level.get("name")
        for key in ("name", "cell", "radius", "chunk_samples", "apron", "class_band",
                    "nodata_fraction", "chunks", "sea"):
            if key not in level:
                problems.append("level {}: {} missing".format(name, key))
        for key, entry in sorted((level.get("chunks") or {}).items()):
            if not _CHUNK_KEY.match(key):
                problems.append("level {}: bad chunk key {!r}".format(name, key))
            if not str(entry.get("file", "")).startswith("{}/{}.".format(name, key)):
                problems.append("level {}: chunk {} file name {!r} does not match".format(
                    name, key, entry.get("file")))
            for extra in ("min", "max"):
                if extra not in entry:
                    problems.append("level {}: chunk {} has no {}".format(name, key, extra))
            where = "level {} chunk {}".format(name, key)
            data = check_entry(where, entry)
            if data is not None and _CHUNK_KEY.match(key):
                _check_chunk(where, level, key, entry, data, manifest["crs"].get("epsg"),
                             problems)
        overlap = set(level.get("sea") or []) & set(level.get("chunks") or {})
        if overlap:
            problems.append("level {}: chunks listed both as sea and as files: {}".format(
                name, sorted(overlap)))
    for key, entry in sorted(manifest["files"].items()):
        check_entry("files.{}".format(key), entry)
    _check_credits(folder, manifest, problems)
    _check_facts(folder, manifest, problems)
    _check_listing(folder, manifest, problems)
    on_disk = {p.relative_to(folder).as_posix() for p in folder.rglob("*") if p.is_file()}
    unlisted = sorted(on_disk - listed - {MANIFEST_NAME})
    if unlisted:
        problems.append("files in the folder but not in the manifest: {}".format(unlisted[:10]))
    return problems
